### ISSUE TITLE
In a monorepo (NPM workspace), file path is not relative to root directory

### ISSUE THREAD

**Issue by SchulteMarkus** [sh33dafi/jest-sonar#57]
In my project I am using [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) for having a monorepo. 

    root/
      packages/
        subdir1/
          __test__/
          src/
        subdir2/
          __test__/
          src/

My testfiles are in the "__test__" directories.

The [Sonar Generic Test Coverage Report Format](https://docs.sonarqube.org/latest/analysis/generic-test/#header-2) requires:
    
> Insert a file element for each file which can be covered by tests. Its path attribute can be either absolute or relative to the root of the module.

In this case, as I have two sub-packages, two sonar-report.xml files are being created.

But in this case, the ```path``` for "file" is not relative to the root directory (or absolute) as required by SonarQube. 
For this reason, SonarQube does not "understand" the sonar-reports.

    <testExecutions version="1">
      <file path="__test__/someSpec.spec.ts"> 
        <testCase name="A name" duration="6" />

**Change request**

Please let file-path be relative to the root-directory in a monorepo, too.

**Comment by sh33dafi** [comment]
Hey @SchulteMarkus can you provide a sample project for me to test with?
That makes it easier for me to verify the fix, thanks

**Comment by sh33dafi** [comment]
> @sh33dafi https://github.com/SchulteMarkus/jest-sonar-57

Thanks I will have a look

**Comment by sh33dafi** [comment]
Hey @SchulteMarkus sorry it took a while to get back to you
but I investigated the issue, the issue won't be fixed by using <rootDir> since jest will see the sub-package as the root dir (since jest is run from that dir)
But you can use the relativeRootDir property to get a correct path in your report

If forked your example and updated the config you can check it [here](https://github.com/sh33dafi/jest-sonar-57)

The output is now 

`<testExecutions version="1">
<file path="packages/b/sub.test.js">
<testCase name="subs 2 - 1 to equal 1" duration="3" />
</file>
</testExecutions>` and `<testExecutions version="1">
<file path="packages/a/sum.test.js">
<testCase name="adds 1 + 2 to equal 3" duration="2" />
</file>
</testExecutions>`

I hope this resolves your issue

**Comment by SchulteMarkus** [comment]
Thanks for your feedback @sh33dafi , I have given it a try - it works!
