### ISSUE TITLE
Clarify repo purpose and relation to jest-sonar-reporter

### ISSUE THREAD

**Issue by friederbluemle** [sh33dafi/jest-sonar#67]
It would be great if the README.md file could be updated with information regarding the relation to [jest-sonar-reporter](https://www.npmjs.com/package/jest-sonar-reporter) and some recommendations.

`jest-sonar-reporter` appears to serve the same exact purpose as `jest-sonar`, and according to npm stats, is **more popular** ([~400k weekly downloads](https://www.npmjs.com/package/jest-sonar-reporter) of `jest-sonar-reporter` vs. [~60k weekly downloads](https://www.npmjs.com/package/jest-sonar) of `jest-sonar`, as of 2023-01-24).
The problem is: `jest-sonar-reporter` was last published 5 years ago, and [its GitHub repo](https://github.com/3dmind/jest-sonar-reporter) has been archived.

The question is: Is `jest-sonar` the "official" replacement? Is there anything users of `jest-sonar-reporter` have to look out for when migrating to `jest-sonar`, or is it a 1:1 switch?

**Comment by sh33dafi** [comment]
Hey there is no relation between this project and jest-sonar-reporter.

This repo servers indeed the same purpose, the reason this repo was created was because jest-sonar-reporter wasn't updated and didn't support a mono-repo setup.

So you can use it as a replacement the output can be parsed by sonar in the same way!
Properties and config for the project is different
